repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.5.0"
    hooks:
    - id: check-yaml
      name: Check YAML files
    - id: trailing-whitespace
      name: Trim trailing whitespaces
  - repo: https://github.com/python-poetry/poetry
    rev: "1.7.0"
    hooks:
    - id: poetry-check
      stages: [push]
      name: Run Poetry check hook