# Specify shared data across all 'output' destinations
# Note that the copier.yml defaults are used whenever the key is not set in this file
[defaults]
repo_name = "snapshot"
project_description = "Snapshot of the skeleton template"
visibility = "private"
github_username = "bswck"
author_username = "bswck"
org_full_name = "bswck"
email_address = "bswck.dev@gmail.com"
publish_on_pypi = false
docs = true
docs_slug = "skeleton-snapshot"
tests = true
package_name = "skeleton_snapshot"
python_version = "3.8"
license_name = "MIT"
use_precommit = true

[output.".ctt/defaults"]

[output.".ctt/no_all"]
package_name = "testing-no-all"
include_all = false
