[tool.poetry]
name = "skeleton"
version = "0.1.0"
description = "The cruft templates for bswck projects."
authors = ["bswck <bswck.dev@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "~3.8"
copier = "^9.0.1"
poethepoet = "^0.24.3"

[tool.poe.tasks]
copier-tasks = "copier-tasks"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
