name: "CTT"

on:
  push:
    branches:
    - "master"

jobs:
  ctt-test:
    name: "Test"
    runs-on: "ubuntu-latest"
    steps:
    - uses: "actions/checkout@v4"
    - name: "Install Redis"
      run: "sudo apt install redis"
    - name: "Install Poetry"
      run: "pipx install poetry"
    - name: "Install dependencies"
      run: "poetry install"
    - uses: "actions/setup-python@v5"
      with:
        cache: "poetry"
    - name: "Run CTT"
      run: "poetry run ctt"
