name: "CTT"

on:
  push:
    branches:
    - "master"

jobs:
  ctt-test:
    name: "Test"
    runs-on: "ubuntu-latest"
    steps:
    - uses: "actions/checkout@v4"
    - uses: "actions/setup-python@v5"
      with:
        python-version: "3.10"
    - name: "Install Redis"
      run: "sudo apt install redis"
    - name: "Run CTT"
      run: "pip-run copier-template-tester copier-templates-extensions -- ctt"
