name: "CTT"

on:
  push:
    branches:
    - "master"

jobs:
  ctt-test:
    name: "Test"
    runs-on: "ubuntu-latest"
    steps:
    - uses: "actions/checkout@v4"
    - name: "Install CTT"
      run: |
        pipx install copier-template-tester
        pipx inject copier-template-tester copier-templates-extensions"
    - name: "Run CTT"
      run: "ctt"
