name: "CTT"
permissions: {}

on:
  push:
    branches:
    - "master"

jobs:
  ctt-test:
    name: "Test"
    runs-on: "ubuntu-latest"
    steps:
    - uses: "actions/checkout@v4"
    - name: "Install CTT"
      run: "pip install copier-template-tester copier-templates-extensions"
    - name: "Test the template"
      run: "python -m ctt"
